### ISSUE TITLE
[UI] Autoselect title on edit

### ISSUE THREAD

**Issue by IreenVL** [justDoji/TraMBU#2]
When you edit a to do and click in the title, it would be nice if the complete title is selected automatyically

**Comment by justDoji** [comment]
Accepted, Implemented and merged.

Changed requirement to: "**When doubleclicking in the title field ...**"
Otherwise the entire text would be continuouly selected when making changes in the title, and the keyboard has to be used to get your cursor.

Acceptable solution?
