### ISSUE TITLE
[UI] Colored Theme - Orange/Yellow

### ISSUE THREAD

**Issue by IreenVL** [justDoji/TraMBU#24]
As a user I would like it if I could choose different themes/colores in which TraMBU is displayed. It would make it more "me" and would also allow me to change things up every once in a while.
As a PO I think more users would be appealed to use (and keep using) TraMBU when they can make it completely the way they want.

Suggested theme: Orange/Yellow

**Comment by IreenVL** [comment]
Red theme finished.
Needs to be uploaded.

![yellorange trambu](https://user-images.githubusercontent.com/50783418/58438011-e5499800-80cc-11e9-8bbb-751608e2baaf.png)

**Comment by justDoji** [comment]
Converted to primefaces theme and added on branch.
