### ISSUE TITLE
[UI] Colord Theme - Pink

### ISSUE THREAD

**Issue by IreenVL** [justDoji/TraMBU#33]
As a user I would like it if I could choose different themes/colores in which TraMBU is displayed. It would make it more "me" and would also allow me to change things up every once in a while.
As a PO I think more users would be appealed to use (and keep using) TraMBU when they can make it completely the way they want.

Suggested theme: Pink

**Comment by IreenVL** [comment]
Done.
Needs to be uploaded to Github.

![pink Trambu](https://user-images.githubusercontent.com/50783418/58374455-b9001100-7f3e-11e9-9b07-6030c56bd43e.png)

**Comment by justDoji** [comment]
PR approved, added to master.
Thanks!
