### ISSUE TITLE
Time tracking

### ISSUE THREAD

**Issue by IreenVL** [justDoji/TraMBU#5]
**Story Outline**
As a professional user
I would like to track how long I'm working on a certain project / to do.
So that I can estimate how long a similar to do will take me + report to my superiors more efficiently.

**Describe the solution you'd like**
Build time tracking in the application on 'to do'-level.

**Comment by justDoji** [comment]
On it

**Comment by justDoji** [comment]
domain + data layer should be good.
Adding loading and writing to file.

Last phase: front-end integration

**Comment by justDoji** [comment]
- Finished up the file -> domain flow of the timelog files.
- Finished cleanup of code: https://sonarcloud.io/dashboard?branch=stories%2Ftimetracking&id=be.doji.productivity%3Anewtrambu

Will work on the downstream flow (domain -> file) before adding anything to the front end.

**Comment by justDoji** [comment]
Demoed, and approved
